language: objective-c

install:
- "gem install xcpretty"
- "gem install xcpretty-travis-formatter"

script:
- "set -e"
- "set -o pipefail"

- "xcodebuild -showsdks"

- "xcodebuild test -target PublicCodeLibrary -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -f `xcpretty-travis-formatter`"
