language: objective-c

before_install:
- "gem install xcpretty --no-rdoc --no-ri --no-document --quiet"

script:
- "set -e"
- "set -o pipefail"

- "xcodebuild -showsdks"

- "xcodebuild test -project PublicCodeLibrary.xcodeproj -scheme PublicCodeLibrary -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO"
