language: objective-c

osx_image: xcode6.4

before_install:
- "gem install xcpretty --no-rdoc --no-ri --no-document --quiet"

script:
- "set -e"
- "set -o pipefail"

- "xcodebuild -showsdks"

- "xcodebuild -scheme PublicCodeLibrary -sdk iphonesimulator test ONLY_ACTIVE_ARCH=NO"
