language: objective-c

osx_image: xcode7.3

install:
- "gem install xcpretty --no-rdoc --no-ri --no-document --quiet"
- "gem install xcpretty-travis-formatter --no-rdoc --no-ri --no-document --quiet"

script:
- "set -e"
- "set -o pipefail"
- "ls -la"

- "xcodebuild -showsdks"

- "xcodebuild -scheme PublicCodeLibrary test | xcpretty -f `xcpretty-travis-formatter`"
